export const ADD_INGREDIENT:'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DEL_INGREDIENT:'DEL_INGREDIENT' = 'DEL_INGREDIENT';
export const CLEAR_INGREDIENTS:'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS';
export const MOVE_INGREDIENTS:'MOVE_INGREDIENTS' = 'MOVE_INGREDIENTS';