export const GET_INGREDIENTS_LIST_REQUEST:'GET_INGREDIENTS_LIST_REQUEST' = 'GET_INGREDIENTS_LIST_REQUEST';
export const GET_INGREDIENTS_LIST_SUCCESS:'GET_INGREDIENTS_LIST_SUCCESS' = 'GET_INGREDIENTS_LIST_SUCCESS';
export const GET_INGREDIENTS_LIST_ERROR:'GET_INGREDIENTS_LIST_ERROR' = 'GET_INGREDIENTS_LIST_ERROR';