export const GET_ORDER_DETAILS_REQUEST:'GET_ORDER_DETAILS_REQUEST' = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS:'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_ERROR:'GET_ORDER_DETAILS_ERROR' = 'GET_ORDER_DETAILS_ERROR';