export const LOGIN_USER_REQUEST:'LOGIN_USER_REQUEST' = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS:'LOGIN_USER_SUCCESS' = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR:'LOGIN_USER_ERROR' = 'LOGIN_USER_ERROR';

export const REGISTER_USER_REQUEST:'REGISTER_USER_REQUEST' = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS:'REGISTER_USER_SUCCESS' = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR:'REGISTER_USER_ERROR' = 'REGISTER_USER_ERROR';

export const LOGOUT_USER_REQUEST:'LOGOUT_USER_REQUEST' = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS:'LOGOUT_USER_SUCCESS' = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR:'LOGOUT_USER_ERROR' = 'LOGOUT_USER_ERROR';

export const GET_USERDATA_REQUEST:'GET_USERDATA_REQUEST' = 'GET_USERDATA_REQUEST';
export const GET_USERDATA_SUCCESS:'GET_USERDATA_SUCCESS' = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_ERROR:'GET_USERDATA_ERROR' = 'GET_USERDATA_ERROR';

export const FORGOT_PASSWORD_REQUEST:'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS:'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR:'FORGOT_PASSWORD_ERROR' = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_REQUEST:'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR:'RESET_PASSWORD_ERROR' = 'RESET_PASSWORD_ERROR';

export const PATCH_USER_REQUEST:'PATCH_USER_REQUEST' = 'PATCH_USER_REQUEST';
export const PATCH_USER_SUCCESS:'PATCH_USER_SUCCESS' = 'PATCH_USER_SUCCESS';
export const PATCH_USER_ERROR:'PATCH_USER_ERROR' = 'PATCH_USER_ERROR';