export const WS_PROFILE_FEED_CONNECTION_START:'WS_PROFILE_FEED_CONNECTION_START' = 'WS_PROFILE_FEED_CONNECTION_START';
export const WS_PROFILE_FEED_CONNECTION_SUCCESS:'WS_PROFILE_FEED_CONNECTION_SUCCESS' = 'WS_PROFILE_FEED_CONNECTION_SUCCESS';
export const WS_PROFILE_FEED_CONNECTION_ERROR:'WS_PROFILE_FEED_CONNECTION_ERROR' = 'WS_PROFILE_FEED_CONNECTION_ERROR';
export const WS_PROFILE_FEED_CONNECTION_CLOSE:'WS_PROFILE_FEED_CONNECTION_CLOSE' = 'WS_PROFILE_FEED_CONNECTION_CLOSE';
export const WS_PROFILE_FEED_GET_MESSAGE:'WS_PROFILE_FEED_GET_MESSAGE' = 'WS_PROFILE_FEED_GET_MESSAGE';
export const WS_PROFILE_FEED_SEND_MESSAGE:'WS_PROFILE_FEED_SEND_MESSAGE' = 'WS_PROFILE_FEED_SEND_MESSAGE';